name: Bandit Security Check

on:
  pull_request:
    branches: [ main, dev ]

jobs:
  security:
    runs-on: demo-devops

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up virtual environment
      run: |
        rm -rf venv_bandit
        python3 -m venv venv_bandit
        source venv_bandit/bin/activate
        
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install bandit
        
    - name: Run bandit
      run: |
        source venv_bandit/bin/activate
        bandit -r Api/ -ll 