name: Secret Scanning

on:
  pull_request:
    branches: [ main, dev ]

jobs:
  secrets:
    runs-on: demo-devops

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up virtual environment
      run: |
        rm -rf venv_trufflehog
        python3 -m venv venv_trufflehog
        
    - name: Install dependencies
      run: |
        source venv_trufflehog/bin/activate
        pip3 install trufflehog jq
        
    - name: Run TruffleHog
      run: |
        source venv_trufflehog/bin/activate
        trufflehog .