name: Secret Scanning

on:
  pull_request:
    branches: [ main, dev ]

jobs:
  secrets:
    runs-on: demo-devops

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up virtual environment
      run: |
        rm -rf venv_detect_secrets
        python3 -m venv venv_detect_secrets
        
    - name: Install dependencies
      run: |
        source venv_detect_secrets/bin/activate
        pip3 install detect-secrets jq
        
    - name: Run Secret Scan
      run: |
        source venv_detect_secrets/bin/activate
        ./scan_secrets.sh