name: Detect Secrets

on:
  pull_request:
    branches: [ main, dev ]

jobs:
  secrets:
    runs-on: demo-devops

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install detect-secrets
        
    - name: Run detect-secrets
      run: |
        detect-secrets scan --fail-on-any 