name: Detect Secrets

on:
  pull_request:
    branches: [ main, dev ]

jobs:
  secrets:
    runs-on: demo-devops

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install detect-secrets
        
    - name: Run detect-secrets
      run: |
        detect-secrets scan --fail-on-any 