name: Flake8

on:
  pull_request:
    branches: [ main, dev ]

jobs:
  lint:
    runs-on: demo-devops

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install flake8
        
    - name: Run flake8
      run: |
        flake8 API 