name: Flake8

on:
  pull_request:
    branches: [ main, dev ]

jobs:
  lint:
    runs-on: demo-devops

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up virtual environment
      run: |
        rm -rf venv_flake8
        python3 -m venv venv_flake8
        source venv_flake8/bin/activate
        
    - name: Install dependencies
      run: |
        pip3 install flake8
        
    - name: Run flake8
      run: |
        source venv_flake8/bin/activate
        flake8 API 