name: Flake8

on:
  pull_request:
    branches: [ main, dev ]

jobs:
  lint:
    runs-on: demo-devops

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.2'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        
    - name: Run flake8
      run: |
        flake8 API 