name: Python Tests

on:
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: demo-devops

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.2'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run pytest
      run: |
        pytest Tests/test_crypto.py -v 